export const data: string[] = [
  "Shammy Kierson Suyat is 19 years old.",
  "Shammy is currently single.",
  "Shammy lives in the Philippines.",
  "Shammy specializes in Application Development.",
  "Shammy's favorite programming language is TypeScript.",
  "Shammy is a Computer Science student.",
  "Shammy Kierson L. Suyat is his complete name.",
  "Shammy's birthday is on October 13, 2005.",
  "Shammy's favorite color is black.",
  "Shammy wants to be a Software Engineer.",
  "Shammy is currently a 3rd year college student.",
  "Shammy studies at University of Makati",
  "Shammy was born and raised in Taguig City",
  "Shammy has one sibling.",
  "Shammy used to play the guitar and sing as hobbies.",
  "Shammy often prefers staying at home rather than going out.",
  "Shammy is more productive at night than in the morning.",
  "Shammy speaks both English and Filipino", 
  "Shammmy's height is 5'9"
];
